docs(store): shorten desc of apps for cleaner view
runtipi/runtipi-appstore pull request #1015
Opened 2023-08-16 01:37 UTC by JigSawFr

This PR aim to give users a cleaner view of app in store and installed.
All ```short_desc``` of apps were rewritten to be cleaner, more precise and comprehensible.
Versions were also bumped to be showed on user interface,
Otherwise, many apps will not be updated due to the fact version is outdated or using latest tag.

Goal: See in 1 look what a app is for.

A screenshot:
![image](https://github.com/meienberger/runtipi-appstore/assets/5781907/336e8653-3a06-4374-9625-b78745914876)

2023-08-16 21:09 UTC, meienberger requested changes

2023-08-16 21:09 UTC, meienberger commented on apps/mylar3/config.json
> +  "name": "Mylar (3)",
I think this should stay `Mylar3` as it is literally the name of the app (based on python3)

2023-08-16 21:09 UTC, meienberger commented on apps/paperless-ngx/config.json
> +  "name": "Paperless (NGX)",
Same here, keep the current name

2024-03-04 18:48 UTC, steveiliop56 commented
@JigSawFr any updates?

2024-03-04 21:01 UTC, meienberger commented
This was a nice work

2024-07-02 20:37 UTC, closed without merging