Add CryptPad
runtipi/runtipi-appstore pull request #12
Opened 2022-09-09 13:30 UTC by sethforprivacy

2022-09-13 13:40 UTC, sethforprivacy commented
Two issues need to be resolved before this can be merged:

- httpUnsafeOrigin and httpSafeOrigin both need to be set, and currently cannot be without mounting a config file, which cannot be dynamic
- The data directory must be chown'd to 4001:4001 for Cryptpad to work, and we have no way to run simple scripts before starting containers ATM.

2022-09-19 09:13 UTC, meienberger commented
Would this work if we create the initial `data` directory with 4001:4001 ?

2022-09-19 15:08 UTC, meienberger commented
I mean if there is a data folder present besides the app config, it gets copied over upon installation. We should try to chown it to 4001:4001

2022-09-19 15:09 UTC, sethforprivacy commented
Ohhh, I get it now.

Yes, I can give that a try and test it out.

2023-10-18 19:21 UTC, steveiliop56 commented
Hello @sethforprivacy, I will rework in the files completely...

2023-10-18 19:23 UTC, steveiliop56 commented on apps/cryptpad/docker-compose.yml
> +      traefik.http.services.cryptpad.loadbalancer.server.port: 80
This needs to be replaced with the new traefik labels...

2023-10-18 19:27 UTC, steveiliop56 requested changes

2023-10-18 19:27 UTC, steveiliop56 commented on apps/cryptpad/docker-compose.yml
> +      traefik.http.services.cryptpad.loadbalancer.server.port: 80
This needs to be replaced with the new traefik labels...

2023-10-18 19:27 UTC, steveiliop56 commented on apps/cryptpad/docker-compose.yml
> +      - ${APP_DATA_DIR}/data/datastores:/cryptpad/datastore
You could just mount ``/cryptpad`` to ``- ${APP_DATA_DIR}/data`` directly...

2023-10-18 19:27 UTC, steveiliop56 commented on apps/cryptpad/docker-compose.yml
> +    image: promasu/cryptpad:nginx
it would be better to use a version.

2023-10-18 19:27 UTC, steveiliop56 commented on apps/cryptpad/config.json
> +  "description": "CryptPad is a collaboration suite that is end-to-end-encrypted and open-source. It is built to enable collaboration, synchronizing changes to documents in real time. Because all dat
That is too big and it will not look welll...

2023-10-18 19:27 UTC, steveiliop56 commented on apps/cryptpad/config.json
> +  "version": "latest",
Here it should have the same version as the image in the docker compose file.

2023-10-18 19:27 UTC, steveiliop56 commented on apps/cryptpad/config.json
> +  "port": 8108,
This port is in use right now...

2023-10-18 19:27 UTC, steveiliop56 commented on apps/cryptpad/metadata/description.md
> +After running the above command, restart the app.
We will recheck this but right now it should be in the top of the readme file.

2023-10-18 19:27 UTC, steveiliop56 commented on apps/cryptpad/metadata/logo.jpg
This definitely needs to  be replaced....

2023-11-26 13:46 UTC, steveiliop56 commented
Closing for inactivity...

2023-11-26 13:46 UTC, closed without merging