Update Wizarr version to 3.4.2, use latest image in docker-compose.ym…
runtipi/runtipi-appstore pull request #1460
Opened 2023-10-24 18:12 UTC by realashleybailey

…l, and add a new logo file

- Version in `config.json` was updated from 2.2.0 to 3.4.2 to reflect the new Wizarr version.
- In `docker-compose.yml`, the image tag was changed from `2.2.0` to `latest` to use the latest Wizarr image.
- The old logo file `logo.jpg` was deleted, and a new logo file `logo.png` was added.

I am the admin of Wizarr for clarification

2023-10-24 19:33 UTC, meienberger requested changes
Thank you for your PR! Have you checked the release notes of wizarr for the breaking v3? Does it work without any action from users to move from v2?

2023-10-24 19:33 UTC, meienberger commented on apps/wizarr/config.json
> +  "version": "latest",
We prefer to use fixed versions for the tag. It avoids unexpected breaking automatic updated (for example 2.2.0 to 3.4.2) Our scripts will automatically update the minor and patch versions

2023-10-24 19:33 UTC, meienberger commented on apps/wizarr/config.json
> +  "short_desc": "Wizarr is a automatic user invitation system for Plex and Jellyfin.",
```suggestion
  "short_desc": "Wizarr is an automatic user invitation system for Plex and Jellyfin.",
```

2023-10-24 19:33 UTC, meienberger commented on apps/wizarr/docker-compose.yml
> +    image: ghcr.io/wizarrrr/wizarr:latest
```suggestion
    image: ghcr.io/wizarrrr/wizarr:3.4.2
```

2023-10-24 19:33 UTC, meienberger commented on apps/wizarr/config.json
> +  "version": "latest",
```suggestion
  "version": "3.4.2",
```

2023-10-24 19:34 UTC, meienberger commented on apps/wizarr/metadata/logo.png
This needs to be a `.jpg` file

2023-10-24 20:41 UTC, realashleybailey commented
> Thank you for your PR! Have you checked the release notes of wizarr for the breaking v3? Does it work without any action from users to move from v2?

Yes, V2 can directly update to V3, I have yet to update the master README to reflect that the latest V3 can auto migrate now.

2023-10-25 05:32 UTC, meienberger commented
> Yes, V2 can directly update to V3, I have yet to update the master README to reflect that the latest V3 can auto migrate now.

Didn't realise you were a Wizarr developer :) well I trust you in this case! Is the PR ready or do you have some work left?

2023-10-25 13:42 UTC, realashleybailey commented
> > Yes, V2 can directly update to V3, I have yet to update the master README to reflect that the latest V3 can auto migrate now.
> 
> 
> 
> Didn't realise you were a Wizarr developer :) well I trust you in this case! Is the PR ready or do you have some work left?
> 
> 
> 
> 

Yes everything is ready I believe ☺️

2023-10-28 08:56 UTC, merged