Add Bitmagnent
runtipi/runtipi-appstore pull request #1600
Opened 2023-11-15 18:38 UTC by DrMxrcy

2023-11-16 12:37 UTC, meienberger requested changes

2023-11-16 12:37 UTC, meienberger commented on apps/bitmagnet/docker-compose.yml
> +      - POSTGRES_PASSWORD=postgres
Should be a variable

2023-11-22 00:05 UTC, DrMxrcy commented
Can we get a re-review?

2023-11-26 13:40 UTC, steveiliop56 commented on apps/bitmagnet/docker-compose.yml
> +      - --keys=dht_crawler
Will that work?

2023-11-27 15:23 UTC, steveiliop56 commented
@DrMxrcy so we merge?

2023-11-27 20:20 UTC, meienberger submitted a review, later dismissed
LGTM (except the logo)

2023-12-07 07:35 UTC, meienberger approved these changes

2023-12-07 07:35 UTC, merged