Add WordPress
runtipi/runtipi-appstore pull request #1679
Opened 2023-11-23 10:33 UTC by Mytraas

## Pull Request Summary

### Docker Compose YAML File (`docker-compose.yml`)

1. WordPress image version `6.4.1`.
2. Utilized environment variables for configuration:
   - `WORDPRESS_DB_HOST` set to `mariadb`.
   - `WORDPRESS_DB_NAME` set using `${DB_NAME}`.
   - `WORDPRESS_DB_USER` set using `${DB_USER}`.
   - `WORDPRESS_DB_PASSWORD` set using `${DB_PASSWORD}`.
3. Defined volumes to persist WordPress data in `${APP_DATA_DIR}/data/wordpress:/var/www/html`.
4. Mapped the container port `${APP_PORT}` to port `80`.
5. Added Traefik labels for routing and HTTPS configuration.
6. Included dependencies on the `mariadb` service.
7. Specified the network as `tipi_main_network`.

### Docker Compose Service (`mariadb`)

1. MariaDB image version `11.1.3`.
2. Used environment variables for MariaDB configuration:
   - `MYSQL_ROOT_PASSWORD` set using `${DB_ROOT_PASSWORD}`.
   - `MYSQL_DATABASE` set using `${DB_NAME}`.
   - `MYSQL_USER` set using `${DB_USER}`.
   - `MYSQL_PASSWORD` set using `${DB_PASSWORD}`.
3. Defined volumes to persist MariaDB data in `${APP_DATA_DIR}/data/mariadb:/var/lib/mysql`.
4. Specified the network as `tipi_main_network`.

### JSON Configuration for WordPress

| Key                          | Value                              |
|------------------------------|------------------------------------|
| "name"                       | "WordPress"                        |
| "available"                  | true                               |
| "port"                       | 8213                               |
| "exposable"                  | true                               |
| "id"                         | "wordpress"                        |
| "description"                | "WordPress is a popular content management system for creating websites and blogs." |
| "tipi_version"               | 1                                  |
| "version"                    | "6.4.1"                            |
| "categories"                 | ["development"]                    |
| "short_desc"                 | "Popular CMS for websites and blogs" |
| "author"                     | "WordPress.org"                    |
| "source"                     | "https://github.com/WordPress/WordPress" |
| "website"                    | "https://wordpress.org"            |
| "form_fields"                | Array of form field objects        |
| "supported_architectures"    | ["amd64", "arm64"]                 |

2023-11-25 16:32 UTC, steveiliop56 requested changes
Hello @Mytraas,

Thank you for the pr! I left you some notes for small things to fix and then we can merge!

2023-11-25 16:32 UTC, steveiliop56 commented on apps/wordpress/config.json
> +  ],
You don't need to ask user to add db details. Please use the random function instead.

2023-11-25 16:32 UTC, steveiliop56 commented on apps/wordpress/docker-compose.yml
> +    container_name: mariadb
Please rename that to something like ```wordpress-db``` or ```wordpress-mariadb```.

2023-11-25 16:32 UTC, steveiliop56 commented on apps/wordpress/docker-compose.yml
> +    restart: always
It would be better to use ```unless-stopped```.

2023-11-25 16:32 UTC, steveiliop56 commented on apps/wordpress/docker-compose.yml
> +    restart: always
It would be better to use ```unless-stopped```

2023-11-25 16:32 UTC, steveiliop56 commented on apps/wordpress/config.json
> +  "categories": ["development"],
I think it would be better to use the social instead of development.

2023-11-26 10:06 UTC, Mytraas commented
I've implemented all the requested changes in my latest commit. Below, you can find a detailed overview of the modifications I've made:

## Summary of Recent Updates

### JSON Configuration (`config.json`)

- Updated "categories" to ["social"] (previously "development").
- Updated "form_fields" with "type": "random" and "min": 32 for enhanced security.

### Docker Compose YAML File (`docker-compose.yml`)

- Renamed the MariaDB container to `wordpress-db`.
- Modified the `WORDPRESS_DB_HOST` environment variable to match the service name with `- WORDPRESS_DB_HOST=wordpress-db`.
- Set the restart policy for both `wordpress` and `wordpress-db` services to `unless-stopped`.

These changes reflect the adjustments made to the configuration files.

2023-11-26 13:16 UTC, steveiliop56 requested changes
Some minor things to fix too.

2023-11-26 13:16 UTC, steveiliop56 commented on apps/wordpress/config.json
> +    },
No need to make the database name random. It would be better to just name it ```wordpress```.

2023-11-26 13:16 UTC, steveiliop56 commented on apps/wordpress/docker-compose.yml
> +    hostname: wordpress
Is the hostname parameter really needed?

2023-11-26 14:45 UTC, Mytraas commented
### Comparison of Configuration Changes

#### Docker Compose YAML File (`docker-compose.yml`)

- Database name is set to `wordpress`.
- Environment variable for `DB_NAME` removed.
- `hostname` removed.

#### JSON Configuration (`config.json`)
- Removed the "Database Name" field from "form_fields" as it's not defined in the Docker Compose file.

2023-11-26 15:21 UTC, steveiliop56 requested changes
Hey @Mytraas,

Almost done! For some reason the previous review didn't pick up an extra comment I added so here it is...

2023-11-26 15:21 UTC, steveiliop56 commented on apps/wordpress/config.json
> +    },
That's not really needed just use ```tipi``` as the user.

2023-11-26 16:35 UTC, steveiliop56 approved these changes

2023-11-26 16:36 UTC, merged